### ISSUE TITLE
Output dumped to stdout instead of being returned

### ISSUE THREAD

**Issue by daelvn** [DarkWiiPlayer/moonxml#1]
See: daelvn/tableview#2

`moonxml` uses `print` to output the generated HTML, and of course, this is not always desired in the case of a library that is supposed to return an HTML string.

A possible and most likely solution is to switch `print` in the environment of the generator, and output into a buffer that can simply be returned.

**Comment by DarkWiiPlayer** [comment]
This is pretty much fixed with the introduction of buffered environments in 6fb4db25feff35aa7f07135169de7d19df11a924
