### ISSUE TITLE
Differences with moonhtml?

### ISSUE THREAD

**Issue by Lukc** [DarkWiiPlayer/moonxml#1]
Hi,

I saw you have two repositories of DSLs for HTML and XML respectively. What is the difference between both projects?

Anyway, having a dedicated DSL instead of having to depend on Lapis is great. :)

Cheers,

**Comment by DarkWiiPlayer** [comment]
Hi,

First of all, thanks for taking interest in moon*ml :)

The difference is mostly about empty tags; in HTML some tags don't need a closing tag like `<br>`, so there's a whitelist of tags where the closing tags just get ommitted.

In XML this is invalid syntax, and instead it creates an empty tag `<my_tag value="data" />` or `<my_tag />` if a tag has no content (`my_tag value: data` or `my_tag!`)

**Comment by Lukc** [comment]
I guess this issue can be closed now, since moonhtml has been merged? :p

**Comment by DarkWiiPlayer** [comment]
Indeed it can :)
