### ISSUE TITLE
Tags without body are not being rendered as mono-atomic

### ISSUE THREAD

**Issue by Lukc** [DarkWiiPlayer/moonxml#3]
Test Case
---

```moon
moonxml = require "moonxml"

render = (f) -> moonxml.xml(f) print

render ->
        svg ->
                rect x: 5, y: 5, width: 90, height: 90
```  
Current Output
---

```xml
<svg>
<rect y="5" x="5" height="90" width="90">
</rect>
</svg>
```

Expected Output
---

```xml
<svg>
<rect y="5" x="5" height="90" width="90"/>
</svg>
```

**Comment by DarkWiiPlayer** [comment]
That's weird... there's a test case for this and it seems to work there.

After testing your code above, I got the following output:

```xml
<svg>
<rect y="5" height="90" width="90" x="5" />
</svg>
```

**Comment by Lukc** [comment]
Maybe this only happens on specific Lua versions? I usually run everything through Lua 5.1.

**Comment by DarkWiiPlayer** [comment]
I ran the tests through Lua 5.3, 5.1 and LuaJIT and they all worked, if I remember correctly. What version are you using? maybe something was broken and *accidentally* got fixed along with the failing test cases?

**Comment by Lukc** [comment]
I updated moonxml and the test now runs fine…

I’m closing this issue since the bug appears to have been fixed.

For the record, I ran the test case using Lua 5.1.5.
